Repository sous-chefs/ntp, pull requests merged in 2023-02, with the labels that each got.

#213 Remove CircleCI
  .circleci/config.yml
  .github/workflows/ci.yml
Labels: Release: Patch, Skip: Announcements

#214 Automated PR: Standardising Files
  CHANGELOG.md
  renovate.json
Labels: Release: Patch, Skip: Announcements

#220 Automated PR: Standardising Files
  .github/workflows/md-links.yml
  .github/workflows/stale.yml
  CHANGELOG.md
Labels: Release: Patch, Skip: Announcements

#221 Remove Delivery and bump required Chef version
  .github/workflows/ci.yml
  CHANGELOG.md
  metadata.rb
Labels: Release: Major, Skip: Announcements

#219 Remove local clock feature
  CHANGELOG.md
  README.md
  attributes/default.rb
  spec/unit/recipes/default_spec.rb
  templates/ntp.conf.erb
Labels: Release: Major

#218 Fix restrict default syntax
  CHANGELOG.md
  attributes/default.rb
  spec/unit/attributes_spec.rb
Labels: Release: Patch

#222 Automated PR: Standardising Files
  .github/workflows/md-links.yml
  CHANGELOG.md
Labels: Release: Patch, Skip: Announcements
