Repository sous-chefs/ntp, pull requests merged in 2024-07, with the labels that each got.

#251 GH-250
  CHANGELOG.md
  attributes/default.rb
  spec/unit/attributes_spec.rb
  templates/ntp.conf.erb
Labels: Feature Request, Release: Minor

#252 Automated PR: Standardising Files
  .github/workflows/ci.yml
  CHANGELOG.md
  kitchen.dokken.yml
  kitchen.global.yml
Labels: Release: Patch, Skip: Announcements

#253 Correct NTPd package choosing under el9
  CHANGELOG.md
  attributes/default.rb
  spec/unit/recipes/default_spec.rb
Labels: Release: Patch
